#!/bin/bash
#
# postinstall script iMac-2001-Catlina 10.15
#
# By chris1111 / Ausdauersportler

if [[ $(sw_vers -productVersion) == "10.15.4" ]]; then
    echo "Latest Catalina"
defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool true
echo "Install plist"
fi

if [[ $(sw_vers -productVersion) == "10.15.5" ]]; then
    echo "Latest Catalina"
defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool true
echo "Install plist"
fi

if [[ $(sw_vers -productVersion) == "10.15.6" ]]; then
    echo "Latest Catalina"
defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool true
echo "Install plist"
fi

if [[ $(sw_vers -productVersion) == "10.15.7" ]]; then
    echo "Latest Catalina"
defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool true
echo "Install plist"
fi

# In the current directory, check for kexts which have been renamed from
# *.kext to *.kext.original, then remove the new versions and rename the
# old versions back into place.
restoreOriginals() {
    if [ -n "`ls -1d *.original`" ]
    then
        for x in *.original
        do
            BASENAME=`echo $x|sed -e 's@.original@@'`
            echo 'Unpatching' $BASENAME
            rm -rf "$BASENAME"
            mv "$x" "$BASENAME"
        done
    fi
}

# Fix permissions on the specified kexts.
fixPerms() {
    chown -R 0:0 "$@"
    chmod -R 755 "$@"
}


#
# check if deinstallation has been selected, run this script and leave
#

if [ -f /"${3}"/tmp/uninstall ]
then
    echo "Remove files previously installed with this package installer"

    defaults write /Library/Preferences/com.apple.security.libraryvalidation.plist DisableLibraryValidation -bool true

    # enter target  /S*/L*/E*
    pushd "${3}/System/Library/Extensions" > /dev/null
    
    rm -rf "./AppleIntelHD3000Graphics.kext"
    rm -rf "./AppleIntelHD3000GraphicsGA.plugin"
    rm -rf "./AppleIntelHD3000GraphicsGLDriver.bundle"
    rm -rf "./AppleIntelHD3000GraphicsVADriver.bundle"

    rm -rf "./AppleIntelSNBGraphicsFB.kext"
    rm -rf "./AppleIntelSNBVA.bundle"

    if [[ $(sw_vers -productVersion) == "10.15.4" ]]; then
        echo "Catalina 10.15.4: restore AppleMCCSControl and IOSurface"
        restoreOriginals
    fi

    if [[ $(sw_vers -productVersion) == "10.15.5" ]]; then
        echo "Catalina 10.15.5: restore AppleMCCSControl and IOSurface"
        restoreOriginals
    fi

    if [[ $(sw_vers -productVersion) == "10.15.6" ]]; then
        echo "Catalina 10.15.6: restore AppleMCCSControl and IOSurface"
        restoreOriginals
    fi

    if [[ $(sw_vers -productVersion) == "10.15.7" ]]; then
        echo "Catalina 10.15.7: restore AppleMCCSControl and IOSurface"
        restoreOriginals
    fi


    /usr/libexec/PlistBuddy -c 'Delete :IOKitPersonalities:AppleGraphicsDevicePolicy:ConfigMap:Mac-942B59F58194171B string none' ./AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist

    /usr/libexec/PlistBuddy -c 'Delete :IOKitPersonalities:AppleGraphicsDevicePolicy:ConfigMap:Mac-942B5BF58194151B string none' ./AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist

    /usr/libexec/PlistBuddy -c 'Delete :IOKitPersonalities:AppleGraphicsDevicePolicy:ConfigMap:Mac-F2268DAE string none' ./AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist

    /usr/libexec/PlistBuddy -c 'Delete :IOKitPersonalities:AppleGraphicsDevicePolicy:ConfigMap:Mac-F2238AC8 string none' ./AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist

    /usr/libexec/PlistBuddy -c 'Delete :IOKitPersonalities:AppleGraphicsDevicePolicy:ConfigMap:Mac-F2238BAE string none' ./AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist

    # these files came additionally, just remove them
    rm -rf "./FakeSMC_CPUSensors.kext"
    rm -rf "./FakeSMC_GPUSensors.kext"
    rm -rf "./FakeSMCKeyStore.kext"

    # these files came additionally, just remove them
    rm -rf "./Lilu.kext"
    rm -rf "./WhateverGreen.kext"

    # these files came additionally, just remove them
    rm -rf "./AppleBacklightFixup.kext"

    # leave target /S*/L*/E*
    popd > /dev/null

    # enter target  /S*/L*/PF*
    pushd "${3}/System/Library/PrivateFrameworks" > /dev/null

    restoreOriginals

    # leave target  /S*/L*/PF*
    popd > /dev/null

    fixPerms "${3}/System/Library/Extensions/"
    fixPerms "${3}/System/Library/PrivateFrameworks/AppleGVA.framework"
else
    # pathing AGC plist
    echo 'Patching AppleGraphicsControl.kext with iMac 2009-2011 board-id'
    /usr/libexec/PlistBuddy -c 'Add :IOKitPersonalities:AppleGraphicsDevicePolicy:ConfigMap:Mac-942B59F58194171B string none' /System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist

    /usr/libexec/PlistBuddy -c 'Add :IOKitPersonalities:AppleGraphicsDevicePolicy:ConfigMap:Mac-942B5BF58194151B string none' /System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist

    /usr/libexec/PlistBuddy -c 'Add :IOKitPersonalities:AppleGraphicsDevicePolicy:ConfigMap:Mac-F2268DAE string none' /System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist

    /usr/libexec/PlistBuddy -c 'Add :IOKitPersonalities:AppleGraphicsDevicePolicy:ConfigMap:Mac-F2238AC8 string none' /System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist

    /usr/libexec/PlistBuddy -c 'Add :IOKitPersonalities:AppleGraphicsDevicePolicy:ConfigMap:Mac-F2238BAE string none' /System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist

    # CAT - Catalina iMac 12,x - save both original folders
    if [ -d /"$3"/tmp/InstallKext/IOSurface.kext ]
    then
        if [ -d "${3}/System/Library/Extensions/IOSurface.kext" ]
        then
            mv "${3}/System/Library/Extensions/IOSurface.kext" "${3}/System/Library/Extensions/IOSurface.kext.original"
        fi
        cp -R /"$3"/tmp/InstallKext/IOSurface.kext "${3}/System/Library/Extensions/"
    fi

    if [ -d /"$3"/tmp/InstallKext/AppleMCCSControl.kext ]
    then
        if [ -d "${3}/System/Library/Extensions/AppleMCCSControl.kext" ]
        then
            mv "${3}/System/Library/Extensions/AppleMCCSControl.kext" "${3}/System/Library/Extensions/AppleMCCSControl.kext.original"
        fi
        cp -R /"$3"/tmp/InstallKext/AppleMCCSControl.kext "${3}/System/Library/Extensions/"
    fi

    # HD3000 new files
    cp -R /"$3"/tmp/InstallKext/AppleIntelHD3000Graphics.kext "${3}/System/Library/Extensions/"
    cp -R /"$3"/tmp/InstallKext/AppleIntelHD3000GraphicsGA.plugin "${3}/System/Library/Extensions/"
    cp -R /"$3"/tmp/InstallKext/AppleIntelHD3000GraphicsGLDriver.bundle "${3}/System/Library/Extensions/"
    cp -R /"$3"/tmp/InstallKext/AppleIntelHD3000GraphicsVADriver.bundle "${3}/System/Library/Extensions/"
    cp -R /"$3"/tmp/InstallKext/AppleIntelSNBGraphicsFB.kext "${3}/System/Library/Extensions/"
    cp -R /"$3"/tmp/InstallKext/AppleIntelSNBVA.bundle "${3}/System/Library/Extensions/"

    # High Sierra AppleGVA Nvidia only - replacement: save the original framework
    if [ -d /"$3"/tmp/AppleGVA/AppleGVA.framework ]
    then
        if [ -d "${3}/System/Library/PrivateFrameworks/AppleGVA.framework" ]
        then
            mv "${3}/System/Library/PrivateFrameworks/AppleGVA.framework" "${3}/System/Library/PrivateFrameworks/AppleGVA.framework.original"
        fi
        cp -R /"$3"/tmp/AppleGVA/AppleGVA.framework "${3}/System/Library/PrivateFrameworks/"
    
        chown -R 0:0 "${3}/System/Library/PrivateFrameworks/AppleGVA.framework"
        chmod -R 755 "${3}/System/Library/PrivateFrameworks/AppleGVA.framework"
    fi

    # vit9696 new files
    cp -R /"$3"/tmp/InstallKext/Lilu.kext "${3}/System/Library/Extensions/"
    cp -R /"$3"/tmp/InstallKext/WhateverGreen.kext "${3}/System/Library/Extensions/"

    # HWMonitor FakeSMC new files
    cp -R /"$3"/tmp/InstallKext/FakeSMC_CPUSensors.kext "${3}/System/Library/Extensions/"
    cp -R /"$3"/tmp/InstallKext/FakeSMC_GPUSensors.kext "${3}/System/Library/Extensions/"
    cp -R /"$3"/tmp/InstallKext/FakeSMCKeyStore.kext "${3}/System/Library/Extensions/"

    # Nvidia (without OpenCore) AppleBacklight Fixup new file
    cp -R /"$3"/tmp/InstallKext/AppleBacklightFixup.kext "${3}/System/Library/Extensions/"

    chown -R 0:0  "${3}/System/Library/Extensions/"
    chmod -R 755  "${3}/System/Library/Extensions/"
fi

# kextcache -i /

# kcditto

"${3}"/usr/sbin/kextcache -i /"${3}"

# calling kcditto from the target volume is the way (mandalorian and according to man pages)
"${3}"/usr/sbin/kcditto

rm -rf /"${3}"/tmp/InstallKext
rm -rf /"${3}"/tmp/AppleGVA
rm -rf /"${3}"/tmp/Install
rm -rf /"${3}"/tmp/uninstall

exit 
